= Sweet Oven-baked Pears
:hp-image: 

:hp-tags: [vegan, pears, maple syrup, butter, dessert]

Life's been pretty crazy, what with moving to Germany, trying to get settled and work/conferences. I finally made time to blog about my food again! If you want to follow my day to day eating habits, you can do so on Instagram - just follow https://www.instagram.com/zestyroxy/[@ZestyRoxy].

For this recipe I used Bosc Pears, they are our favourite every day pears, but they are also great for baking; they keep their shape and don't get all soggy. 


+++<u>Ingredients</u>+++
[square]
* 2 Bosc pears (1 per person)
* maple syrup
* 2 tbsp vegan butter
* 1/4 lemon juice
* 1/2 tsp nutmeg
* 1/2 tsp cloves
* 1 tsp cinnamon

+++<u>Instructions</u>+++
[square]
* Preheat your oven to 240 C.
* Fill the bottom of your ceramic or glass baking dish with 0.5 cm of maple syrup. Add two tablespoons of butter and place the dish in the over to melt the butter.
* Cut your pears in half lengthwise. Cut off the stems and scoop out the hearts with a spoon.
* Once the butter is melted, add the lemon juice and use a fork to combine the ingredients. 
* Add spices to the maple syrup mixture and stir to combine well.
* Place your pears face down into the dish and cover it with foil, the liquid will boil and splatter all over if you don't :) 
* Bake for 20 minutes; flipping halfway through. Once the 20 minutes are over, poke the largest pear with a fork, if it doesn't slide in easily, bake for another 5 minutes. 


+++<u>Presentation</u>+++

We served ours with chocolate ice cream and covered them with the hot gooey maple syrup butter sauce left in the casserole dish. I think many options would be delicious.
[square]
* cover them maple syrup sauce and powdered sugar
* cut up the pears and use them and the sauce as oatmeal toppings
* serve them with vegan vanilla ice cream and walnuts
* nice side to a piece of cake
* top them with your favourite muesli or granola and coconut whip cream
* so many possibilities! 

image::#small[Vegan Baked Pears]

Enjoy!