= Vegan Olive Oil & Sea Salt Brownie Cookies
:hp-image: 

:hp-tags: [recipe, vegan, cookies, chocolate, olive oil, brownie, sea salt]


Disclaimer - the original recipe for these cookies belongs to http://butterlustblog.com/2013/08/06/olive-oil-sea-salt-brownie-cookies/[Butterlust] Katie. They were my favourite cookies and so I slightly modified the recipe to make them vegan. Thank you for the wonderful recipe Katie! 

+++<u>Ingredients</u>+++
[square]
- 1/2 cup olive oil
- 1 cup white sugar
- 2 egg replacers - I used https://www.amazon.de/Arche-Veg-Egg-175-Bio/dp/B00LB19TIQ[VegEgg]
- 3/4 cup white flour
- 3/4 cup natural cocoa powder
- 1/2 tsp sea salt, plus more for sprinkling
- 1 tsp baking soda
- 1 tbsp hot water
- 1 tsp vanilla sugar
- 150 g of vegan chocolate chopped or vegan chocolate chips - I used http://www.vivani-chocolate.de/P_Cooking_Chocolate_Rice_Choc.html[Vivani's Rice Choc Cooking Chocolate]

+++<u>Instructions</u>+++
[square]
- Do not start your oven yet - the batter needs to be refrigerated.
- Prepare your egg replacer and let it sit.
- In a large bowl, add the olive oil and sugar and mix until well combined.
- Add the egg replacer, mixing well until combined.
- Add the cocoa powder, flour, and salt and beat until a dough forms - it should be the consistency of a thick brownie batter.
- In a small bowl, dissolve the baking soda into the hot water. Add dissolved baking soda and vanilla and beat until well combined.
- Stir in the chocolate in the batter with a spatula.
- Refrigerate the batter for at least 30 minutes, up to overnight.
- When ready to bake, preheat oven to 350 degrees (176°C) and line baking sheets with parchment paper.
- Once the oven is ready, take the batter out of the fridge and scoop out heaping tablespoons onto your prepared baking sheets and sprinkle with sea salt. It should yield 12 large cookies.
- Bake for 10 minutes, or until edges are set.
- Let cool completely on the baking sheets then transfer to a wire rack to cool.

Enjoy! Remember to share with your friends.