= Vegan food in Leipzig | Weekend Trip
:hp-image: 

:hp-tags: [travel, leipzig, germany, restaurants, vegan]

This weekened, we travelled south to visit Leipzig, one of our favourite cities! We were very excited to explore the Christmas Market (Weihnachtsmarkt) because it's so beautiful and to discover vegan restaurants and store in a different city.

image::[Leipzig Germany]

== Friday
We left Kiel early afternoon and spent the trainride working, which means we were tired when we got to the city. It was cold and we only wanted to get to our Airbnb near the city centre, it was only 3 tram stops from the main train station or a 15 min walk to downtown.

image:: [backyard art]

The plan was to eat at http://restaurant-greensoul.de/[Green Soul] located near our apartment. It looks like an amazing vegetarian/vegan restaurant! I had been dreaming of their walnut burger for weeks.

Unfortunately, it was too late to make it in time to eat there. We tried ordering on Foodora, but that didn't work out because of a technical problem on Foodora's side. Sadly, we never made it to Green Soul since we had other plans on Saturday and the restaurant is closed on Sundays. I will make a point to eat there next time I visit.

By 22:30 we made it to a sushi place we like called Mr. Moto. They have really tasty veggie california rolls http://mrmoto.de/[Mr. Moto]. Unfortunately, it seems like their vegetarian sushi's aren't vegan, but we were too hungry and didn't find other vegan alternatives.

== Saturday
Saturday morning, we had plans to visit the Christmas market with my boyfriend, Stefan's family. Before meeting up with them, we stopped by http://www.goodies-berlin.de/kategorie/leipzig/[Goodies] and [Veganz]. For breakfast we had, this amazing vegan egg salad bagel. It is made with chickpeas, spelled pasta with fresh herbs and tomato. It's so delicious.

image:: [Goodies vegan egg salad bagel]

https://scontent-ams3-1.xx.fbcdn.net/v/t1.0-9/11822584_393313290854297_6260908603392112078_n.jpg?oh=3924b743013ae83c67335dcf7221724e&oe=58C0965B[photo credit: Goodies Facebook]

We also had a Get up and Goji Smoothie. It's made with Fresh pineapples, strawberries, gojibeberries, banana, and orange juice. It was like a punch of freshness in the face. Definitely made me get up and go. 

Of course we also had coffee, a soy cappuccino and a peanut butter latte. My peanut butter latte was definitely interesting, and tasted good, but a lot of peanut butter was left at the bottom once the coffee was gone.

Goodies on https://www.facebook.com/goodies.leipzig/[Facebook]

